25/ 08/ 26

In [4]:
pip list

Package                           Version
--------------------------------- --------------------
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
aiobotocore                       2.25.0
aiodns                            3.5.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.13.2
aioitertools                      0.12.0
aiosignal                         1.4.0
alabaster                         0.7.16
alembic                           1.18.4
altair                            5.5.0
anaconda-anon-usage               0.7.5
anaconda-auth                     0.12.3
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.7.0
anaconda-client                   1.14.0
anaconda-navigator                2.7.0
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.10.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                           0.1.4
appscript                         1.4.0
archspec                          0.2.5
argon2-cffi                       21.3.0
argon2-cffi-bindings              25.1.0
arrow                             1.4.0
astroid                           3.3.11
astropy                           7.1.1
astropy-iers-data                 0.2025.11.10.0.38.31
asttokens                         3.0.0
async-lru                         2.0.5
asyncssh                          2.21.1
atomicwrites                      1.4.0
attrs                             25.4.0
Automat                           24.8.1
autopep8                          2.0.4
babel                             2.17.0
bcrypt                            5.0.0
beautifulsoup4                    4.13.5
binaryornot                       0.4.4
black                             25.9.0
bleach                            6.3.0
blinker                           1.9.0
bokeh                             3.8.0
boltons                           25.0.0
botocore                          1.40.46
Bottleneck                        1.4.2
brotlicffi                        1.1.0.0
cachetools                        5.5.1
cattrs                            25.3.0
certifi                           2026.1.4
cffi                              2.0.0
chardet                           5.2.0
charset-normalizer                3.4.4
click                             8.2.1
cloudpickle                       3.1.1
colorcet                          3.1.0
comm                              0.2.3
conda                             26.1.1
conda-anaconda-telemetry          0.3.0
conda-anaconda-tos                0.2.2
conda-build                       25.11.1
conda-content-trust               0.2.0
conda_index                       0.7.0
conda-libmamba-solver             25.11.0
conda-pack                        0.8.1
conda-package-handling            2.4.0
conda_package_streaming           0.12.0
conda-repo-cli                    1.0.173
constantly                        23.10.4
contourpy                         1.3.3
cookiecutter                      2.6.0
cryptography                      46.0.3
cssselect                         1.2.0
cycler                            0.11.0
dask                              2025.11.0
datashader                        0.18.2
debugpy                           1.8.16
decorator                         5.2.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.4.0
distributed                       2025.11.0
distro                            1.9.0
dmglib                            0.9.5
docstring-to-markdown             0.17
docutils                          0.21.2
et_xmlfile                        2.0.0
evalidate                         2.0.3
executing                         2.2.1
fastjsonschema                    2.21.2
filelock                          3.20.0
flake8                            7.1.1
Flask                             3.1.2
fonttools                         4.60.1
frozendict                        2.4.6
frozenlist                        1.8.0
fsspec                            2025.10.0
gitdb                             4.0.12
GitPython                         3.1.45
gmpy2                             2.2.1
greenlet                          3.2.4
h11                               0.16.0
h5py                              3.15.1
HeapDict                          1.0.1
holoviews                         1.22.0
html5lib                          1.1
httpcore                          1.0.9
httpx                             0.28.1
hvplot                            0.12.1
hyperlink                         21.0.0
idna                              3.11
ImageIO                           2.37.2
imagesize                         1.4.1
imbalanced-learn                  0.14.0
importlib_metadata                8.7.0
incremental                       24.7.2
inflection                        0.5.1
iniconfig                         2.1.0
intake                            2.0.8
intervaltree                      3.1.0
ipykernel                         6.31.0
ipympl                            0.9.7
ipython                           9.7.0
ipython_pygments_lexers           1.1.1
ipywidgets                        8.1.7
isort                             6.1.0
itemadapter                       0.12.1
itemloaders                       1.3.2
itsdangerous                      2.2.0
jaraco.classes                    3.4.0
jaraco.context                    0.0.0
jaraco.functools                  4.1.0
jedi                              0.19.2
jellyfish                         1.2.1
Jinja2                            3.1.6
jmespath                          1.0.1
joblib                            1.5.2
json5                             0.12.1
jsonpatch                         1.33
jsonpointer                       3.0.0
jsonschema                        4.25.0
jsonschema-specifications         2025.9.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.8.1
jupyter-events                    0.12.0
jupyter-lsp                       2.2.5
jupyter_server                    2.16.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.4.7
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.28.0
jupyterlab_widgets                3.0.15
keyring                           25.7.0
kiwisolver                        1.4.9
lazy_loader                       0.4
lckr_jupyterlab_variableinspector 3.2.4
libarchive-c                      5.1
libmambapy                        2.3.2
lief                              0.16.4
linkify-it-py                     2.0.3
llvmlite                          0.45.1
lmdb                              1.7.5
locket                            1.0.0
lsprotocol                        2025.0.0
lxml                              5.3.0
lz4                               4.4.5
Mako                              1.3.10
Markdown                          3.8
markdown-it-py                    2.2.0
MarkupSafe                        3.0.2
matplotlib                        3.10.6
matplotlib-inline                 0.2.1
mccabe                            0.7.0
mdit-py-plugins                   0.5.0
mdurl                             0.1.2
menuinst                          2.4.2
mistune                           3.1.2
more-itertools                    10.8.0
mpi4py                            4.0.3
mpmath                            1.3.0
msgpack                           1.1.1
multidict                         6.7.0
multipledispatch                  1.0.0
mypy                              1.17.1
mypy_extensions                   1.0.0
narwhals                          2.7.0
navigator-updater                 0.6.0
nb_conda_kernels                  2.5.2
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest_asyncio                      1.6.0
networkx                          3.5
nltk                              3.9.2
notebook                          7.4.5
notebook_shim                     0.2.4
numba                             0.62.1
numexpr                           2.14.1
numpy                             2.3.5
numpydoc                          1.9.0
openpyxl                          3.1.5
overrides                         7.7.0
packaging                         25.0
pandas                            2.3.3
pandocfilters                     1.5.1
panel                             1.8.3
param                             2.3.0
parsel                            1.10.0
parso                             0.8.5
partd                             1.4.2
pathspec                          0.12.1
patsy                             1.0.1
pexpect                           4.9.0
pickleshare                       0.7.5
pillow                            12.0.0
pip                               25.3
pkce                              1.0.3
pkginfo                           1.12.1.2
platformdirs                      4.5.0
plotly                            6.3.0
pluggy                            1.5.0
prometheus_client                 0.21.1
prompt_toolkit                    3.0.52
propcache                         0.3.1
Protego                           0.4.0
protobuf                          5.29.3
psutil                            7.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyarrow                           21.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.2
pycares                           4.10.0
pycodestyle                       2.12.1
pycosat                           0.6.6
pycparser                         2.23
pyct                              0.6.0
pycurl                            7.45.7
pydantic                          2.12.4
pydantic_core                     2.41.5
pydantic-settings                 2.12.0
PyDispatcher                      2.0.7
pydocstyle                        6.3.0
pyerfa                            2.0.1.5
pyflakes                          3.2.0
PyGithub                          2.8.1
Pygments                          2.19.2
PyJWT                             2.10.1
pylint                            3.3.8
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyNaCl                            1.6.0
pyobjc-core                       12.1
pyobjc-framework-Cocoa            12.1
pyobjc-framework-CoreServices     12.1
pyobjc-framework-FSEvents         12.1
pyodbc                            5.3.0
pyOpenSSL                         25.3.0
pyparsing                         3.2.5
PyQt5                             5.15.11
PyQt5_sip                         12.17.0
PyQtWebEngine                     5.15.7
PySide6                           6.9.2
PySocks                           1.7.1
pytest                            8.4.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.1.0
python-json-logger                3.2.1
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-ruff                   2.3.0
python-lsp-server                 1.13.1
python-slugify                    8.0.4
pytokens                          0.3.0
pytoolconfig                      1.2.6
pytz                              2025.2
pyuca                             1.2
pyviz_comms                       3.0.6
PyWavelets                        1.9.0
PyYAML                            6.0.3
pyzmq                             27.1.0
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.4.0
qtconsole                         5.7.0
QtPy                              2.4.3
queuelib                          1.8.0
readchar                          4.2.1
referencing                       0.37.0
regex                             2025.9.1
requests                          2.32.5
requests-file                     2.1.0
requests-toolbelt                 1.0.0
rfc3339_validator                 0.1.4
rfc3986_validator                 0.1.1
rich                              14.2.0
roman-numerals-py                 3.1.0
rope                              1.14.0
rpds-py                           0.28.0
rtree                             1.4.1
ruamel.yaml                       0.18.16
ruamel.yaml.clib                  0.2.14
ruamel_yaml_conda                 0.17.21
ruff                              0.12.0
s3fs                              2025.10.0
scikit-image                      0.25.2
scikit-learn                      1.7.2
scipy                             1.16.3
Scrapy                            2.13.3
seaborn                           0.13.2
semver                            3.0.4
Send2Trash                        1.8.2
sentry-sdk                        2.45.0
service-identity                  24.2.0
setuptools                        80.9.0
shellingham                       1.5.4
shiboken6                         6.9.2
sip                               6.12.0
six                               1.17.0
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   3.0.1
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            8.2.3
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
spyder                            6.1.0
spyder-kernels                    3.1.1
SQLAlchemy                        2.0.43
stack_data                        0.6.3
statsmodels                       0.14.5
streamlit                         1.51.0
superqt                           0.7.6
sympy                             1.14.0
tables                            3.10.2
tabulate                          0.9.0
tblib                             3.1.0
tenacity                          9.1.2
terminado                         0.18.1
text-unidecode                    1.3
textdistance                      4.6.3
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2025.10.4
tinycss2                          1.4.0
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.2.1
tomlkit                           0.13.3
toolz                             1.0.0
tornado                           6.5.1
tqdm                              4.67.1
traitlets                         5.14.3
truststore                        0.10.1
Twisted                           25.5.0
typer                             0.20.0
typer-slim                        0.20.0
typing_extensions                 4.15.0
typing-inspection                 0.4.2
tzdata                            2025.2
uc-micro-py                       1.0.3
ujson                             5.11.0
urllib3                           2.5.0
uvloop                            0.22.1
w3lib                             2.3.1
watchdog                          4.0.2
wcwidth                           0.2.13
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.1.3
whatthepatch                      1.0.7
wheel                             0.45.1
widgetsnbextension                4.0.14
wrapt                             1.17.0
wurlitzer                         3.1.1
xarray                            2025.10.1
xlwings                           0.33.15
xyzservices                       2025.4.0
yapf                              0.43.0
yarl                              1.22.0
zict                              3.0.0
zipp                              3.23.0
zope.interface                    8.0.1
zstandard                         0.24.0
Note: you may need to restart the kernel to use updated packages.

In [79]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [2]:
%pdoc pd

Class docstring:
    pandas - a powerful data analysis and manipulation library for Python
    =====================================================================

    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.

    Main Features
    -------------
    Here are just a few of the things that pandas does well:

      - Easy handling of missing data in floating point as well as non-floating
        point data.
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic and explicit data alignment: objects can be explicitly aligned
        to a set of labels, or the user can simply ignore the labels and let
        `Series`, `DataFrame`, etc. automatically align the data for you in
        computations.
      - Powerful, flexible group by functionality to perform split-apply-combine
        operations on data sets, for both aggregating and transforming data.
      - Make it easy to convert ragged, differently-indexed data in other Python
        and NumPy data structures into DataFrame objects.
      - Intelligent label-based slicing, fancy indexing, and subsetting of large
        data sets.
      - Intuitive merging and joining data sets.
      - Flexible reshaping and pivoting of data sets.
      - Hierarchical labeling of axes (possible to have multiple labels per tick).
      - Robust IO tools for loading data from flat files (CSV and delimited),
        Excel files, databases, and saving/loading data from the ultrafast HDF5
        format.
      - Time series-specific functionality: date range generation and frequency
        conversion, moving window statistics, date shifting and lagging.

In [7]:
data = [1, 2, 3, 4, 7, 77]
s = pd.Series(data)

s

0     1
1     2
2     3
3     4
4     7
5    77
dtype: int64

In [8]:
s.values

array([ 1,  2,  3,  4,  7, 77])

In [9]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [10]:
# let's create a Series with an index identifying each data point with a label

data = [x * 10 for x in range(5)]

s = pd.Series(data, index=['a', 'b', 'c', 'e', 'f'])

s

a     0
b    10
c    20
e    30
f    40
dtype: int64

In [11]:
s.index

Index(['a', 'b', 'c', 'e', 'f'], dtype='object')

In [12]:
# s[3]
s.iloc[3] # integer location

np.int64(30)

In [13]:
s[:3]

a     0
b    10
c    20
dtype: int64

In [14]:
# By label dict
s ['a']

np.int64(0)

In [15]:
# to select multiple rowa or elements, use a list of labels

s[['a', 'e']]

a     0
e    30
dtype: int64

In [16]:
# Using .loc and .iloc
# Note: loc selects data using row and column names (labels),
# while iloc uses number positions (integers from 0 to n-1).
# When you slice a range, loc includes the last item, but iloc stops before the last item
# Label-based
print(s.loc['b'])

10

In [17]:
# Position -based 

print(s.iloc[1])

10

In [18]:
s[4] = 50

/var/folders/r5/4k_jrps502s1wr2pyxpkh6dw0000gn/T/ipykernel_85578/3410906351.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s[4] = 50

In [19]:
s

a     0
b    10
c    20
e    30
f    50
dtype: int64

In [20]:
# Series operation
s+5

a     5
b    15
c    25
e    35
f    55
dtype: int64

In [21]:
s*2

a      0
b     20
c     40
e     60
f    100
dtype: int64

In [22]:
# Bolean operation

s > 10

a    False
b    False
c     True
e     True
f     True
dtype: bool

In [23]:
# filtering with condition
s[s > 15]

c    20
e    30
f    50
dtype: int64

Another way to think about a Series is as a fixed-length, ordered dict, as it is a
mapping of index values to data values. It can be used in many contexts where
you might use a dict:

In [25]:
'b' in s    # membership

True

In [24]:
# You can also create a series from a dictionary
# Note: if you pass a list, pd assigns it index (or you assign your index
# but if you pass a dict, pd uses the key as index (label).
sdata = {
'Kwara': 'Ilorin',
'Ondo': 'Akure',
'Lagos': 'Ikeja',
'Oyo': 'Ibadan'
}
s2 = pd.Series(sdata)
s

a     0
b    10
c    20
e    30
f    50
dtype: int64

In [ ]:
Handling Missing Data (None or np.nan)

s.is

## Name Attribute and Index Manipulation

In [26]:
s.name

In [28]:
s.name = 'test data'

In [29]:
s.name

'test data'

In [30]:
# Setting or changing index

s.index = ['x', 'y', 'z', 'w', 'v']

s.index

Index(['x', 'y', 'z', 'w', 'v'], dtype='object')

In [31]:
s

x     0
y    10
z    20
w    30
v    50
Name: test data, dtype: int64

In [32]:
# Resetting index 

s = s.reset_index(drop=True)

## DataFrame (2D)

Each column is essentially a Series.
Supports row and column indexing.
Offers powerful grouping, filtering, aggregation, reshaping, and merging
capabilities.

In [33]:
data = {
    'Name': ['Hannah', 'Zainab', 'Tomi', 'Funmi'],
    'Age': [15, 20, 18, 25],
    'City': ['Ilorin', 'Lagos', 'Ibadan', 'Abuja']
}
df = pd.DataFrame(data)
df

     Name  Age    City
0  Hannah   15  Ilorin
1  Zainab   20   Lagos
2    Tomi   18  Ibadan
3   Funmi   25   Abuja

In [34]:
index =['one', 'two', 'three', 'four']
df = pd.DataFrame(data, index=index)
df

         Name  Age    City
one    Hannah   15  Ilorin
two    Zainab   20   Lagos
three    Tomi   18  Ibadan
four    Funmi   25   Abuja

In [35]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [36]:
df ['Name']     # check what happen here

one      Hannah
two      Zainab
three      Tomi
four      Funmi
Name: Name, dtype: object

In [ ]:
# Please, Note: df[column name] works for any column name,
# but df.column only works when the column name is a valid Python variabl
df.Age

In [38]:
data = {
'Name': ['Adeola', 'Arafat', 'Nofi', 'Salamat'],
'Age': [25, 30, 35, 10],
'City': ['Ilorin', 'Lagos', 'Ibadan', 'Abuja']
}
df = pd.DataFrame(data)
df
# Note: When you are assigning lists or arrays to a column, the value’s length must match the length of the DataFrame.

      Name  Age    City
0   Adeola   25  Ilorin
1   Arafat   30   Lagos
2     Nofi   35  Ibadan
3  Salamat   10   Abuja

In [39]:
df.T

           0       1       2        3
Name  Adeola  Arafat    Nofi  Salamat
Age       25      30      35       10
City  Ilorin   Lagos  Ibadan    Abuja

In [72]:
# Row with label/index
df.loc[0]

Survived                         0
Pclass                           3
Name        Mr. Owen Harris Braund
Sex                           male
Age                           22.0
SibSp                            1
PaCh                             0
Fare                          7.25
Name: 0, dtype: object

In [74]:
# selecting by condition

df[df['Age'] > 60 ]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500
169,0,1,Mr. Wyckoff Van der hoef,male,61.0,0,0,33.5000
251,0,1,Mr. William Thomas Stead,male,62.0,0,0,26.5500
273,1,1,Miss. Kornelia Theodosia Andrews,female,63.0,1,0,77.9583
278,0,3,Mr. Frank Duane,male,65.0,0,0,7.7500
324,0,3,Mr. Johan Hansen Nysveen,male,61.0,0,0,6.2375
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
453,0,1,Mr. Francis Davis Millet,male,65.0,0,0,26.5500
480,1,3,Mrs. (Hedwig) Turkula,female,63.0,0,0,9.5875
490,0,1,Mr. Ramon Artagaveytia,male,71.0,0,0,49.5042
508,0,3,Mr. James Webber,male,66.0,0,0,8.0500
535,0,3,Mr. Samuel Beard Risien,male,69.0,0,0,14.5000
542,0,1,Mr. Arthur Ernest Nicholson,male,64.0,0,0,26.0000
552,0,1,Mr. George Wright,male,62.0,0,0,26.5500
561,0,3,Miss. (Marion Ogden) Meanwell,female,62.0,0,0,8.0500
567,1,2,Mr. George Harris,male,62.0,0,0,10.5000
622,0,1,Mr. Frederick Sutton,male,61.0,0,0,32.3208
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.0,0,0,30.0000
669,0,2,Mr. Henry Michael Mitchell,male,70.0,0,0,10.5000
741,0,1,Capt. Edward Gifford Crosby,male,70.0,1,1,71.0000
825,1,1,Mrs. George Nelson (Martha Evelyn) Stone,female,62.0,0,0,80.0000
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.7750

In [75]:
# Mixed selection
# format: df.loc[row_indexer, column_indexer]

df.loc[0, 'Name']

'Mr. Owen Harris Braund'

In [76]:
df.iloc [0, 2] # remember: col

'Mr. Owen Harris Braund'

In [77]:
# Rows from index 0 to 2 (inclusive)

df.loc[0:2]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250

In [78]:
# All rows, selected columns

df.loc[:, ['Name', 'Age']]

                                                  Name   Age
0                               Mr. Owen Harris Braund  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                                Miss. Laina Heikkinen  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
..                                                 ...   ...
882                               Rev. Juozas Montvila  27.0
883                        Miss. Margaret Edith Graham  19.0
884                     Miss. Catherine Helen Johnston   7.0
885                               Mr. Karl Howell Behr  26.0
886                                 Mr. Patrick Dooley  32.0

[887 rows x 2 columns]

In [81]:
# selecting based on condition     31/08/26

df[df['Age'] > 60]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500
169,0,1,Mr. Wyckoff Van der hoef,male,61.0,0,0,33.5000
251,0,1,Mr. William Thomas Stead,male,62.0,0,0,26.5500
273,1,1,Miss. Kornelia Theodosia Andrews,female,63.0,1,0,77.9583
278,0,3,Mr. Frank Duane,male,65.0,0,0,7.7500
324,0,3,Mr. Johan Hansen Nysveen,male,61.0,0,0,6.2375
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
453,0,1,Mr. Francis Davis Millet,male,65.0,0,0,26.5500
480,1,3,Mrs. (Hedwig) Turkula,female,63.0,0,0,9.5875
490,0,1,Mr. Ramon Artagaveytia,male,71.0,0,0,49.5042
508,0,3,Mr. James Webber,male,66.0,0,0,8.0500
535,0,3,Mr. Samuel Beard Risien,male,69.0,0,0,14.5000
542,0,1,Mr. Arthur Ernest Nicholson,male,64.0,0,0,26.0000
552,0,1,Mr. George Wright,male,62.0,0,0,26.5500
561,0,3,Miss. (Marion Ogden) Meanwell,female,62.0,0,0,8.0500
567,1,2,Mr. George Harris,male,62.0,0,0,10.5000
622,0,1,Mr. Frederick Sutton,male,61.0,0,0,32.3208
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.0,0,0,30.0000
669,0,2,Mr. Henry Michael Mitchell,male,70.0,0,0,10.5000
741,0,1,Capt. Edward Gifford Crosby,male,70.0,1,1,71.0000
825,1,1,Mrs. George Nelson (Martha Evelyn) Stone,female,62.0,0,0,80.0000
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.7750

In [82]:
# Mixed selection
# Format: df. loc[row_indexer, column_indexer]

df.loc[0, 'Name']

'Mr. Owen Harris Braund'

In [83]:
df.iloc[0, 2] # remember: cols are also indexed

'Mr. Owen Harris Braund'

In [85]:
# All rows, selected columns

df.loc[:, ['Name', 'Age']]

                                                  Name   Age
0                               Mr. Owen Harris Braund  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                                Miss. Laina Heikkinen  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
..                                                 ...   ...
882                               Rev. Juozas Montvila  27.0
883                        Miss. Margaret Edith Graham  19.0
884                     Miss. Catherine Helen Johnston   7.0
885                               Mr. Karl Howell Behr  26.0
886                                 Mr. Patrick Dooley  32.0

[887 rows x 2 columns]

In [86]:
# Names where Age > 30

df.loc[df['Age'] > 30, 'Name']

1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
6                                 Mr. Timothy J McCarthy
11                               Miss. Elizabeth Bonnell
                             ...
869                           Mr. Victor Vander Cruyssen
875         Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
877                                    Mr. Johann Markun
881                  Mrs. William (Margaret Norton) Rice
886                                   Mr. Patrick Dooley
Name: Name, Length: 362, dtype: object

In [88]:
df.loc[df['Age'] > 60, 'Sex']

33       male
53       male
63       male
95       male
115      male
169      male
251      male
273    female
278      male
324      male
435      male
453      male
480    female
490      male
508      male
535      male
542      male
552      male
561    female
567      male
622      male
627      male
669      male
741      male
825    female
847      male
Name: Sex, dtype: object

In [ ]:
# Quick task, return name and age of those >= 70

In [92]:
df.loc[df['Age'] > 70, ['Name','Age']]

                                    Name   Age
95              Mr. George B Goldschmidt  71.0
115                  Mr. Patrick Connors  70.5
490               Mr. Ramon Artagaveytia  71.0
627  Mr. Algernon Henry Wilson Barkworth  80.0
847                   Mr. Johan Svensson  74.0

## Basic Operation

In [94]:
# Filtering

# Simple condition
df[df['Fare'] > 250]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0000
87,1,1,Miss. Mabel Helen Fortune,female,23.0,3,2,263.0000
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
309,1,1,Miss. Emily Borie Ryerson,female,18.0,2,2,262.3750
339,1,1,Miss. Alice Elizabeth Fortune,female,24.0,3,2,263.0000
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292
738,1,1,Miss. Susan Parker Ryerson,female,21.0,2,2,262.3750

In [ ]:
# Combined/multiple conditions

# try or aswell

In [95]:
df[(df['Age'] > 25) & (df['Fare'] > 250)]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292

In [99]:
df[(df['Age'] > 25) | (df['Fare'] > 250)]   # or |

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
...,...,...,...,...,...,...,...,...
879,0,2,Mr. Frederick James Banfield,male,28.0,0,0,10.5000
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [100]:
# String condition

df[df['Name'].str.contains('Rose')]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
851,1,3,Mrs. Sam (Leah Rosen) Aks,female,18.0,0,1,9.35

In [101]:
# String condition
df[df['Name'].str.contains('Arafat')]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, SibSp, PaCh, Fare]
Index: []

In [ ]:
# class task
# select all where sex=female and survived=0

In [105]:
df[(df['Sex'] == 'female') & (df['Survived'] == 0)]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
24,0,3,Miss. Torborg Danira Palsson,female,8.0,3,1,21.0750
38,0,3,Miss. Augusta Maria Vander Planke,female,18.0,2,0,18.0000
40,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40.0,1,0,9.4750
...,...,...,...,...,...,...,...,...
850,0,2,Mrs. Ernest Courtenay (Lilian Hughes) Carter,female,44.0,1,0,26.0000
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.5500
878,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500

Setting and Resetting Indexes

In [106]:
# Set a column as index
df.set_index('Name', inplace=True)       # how do i make a copy

In [107]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
Name,,,,,,,
Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,female,38.0,1,0,71.2833
Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500

In [108]:
df.set_index('Name', inplace=False)

KeyError: "None of ['Name'] are in the columns"

In [109]:
# Reset index back to default
df.reset_index(inplace=True)

In [110]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500

In [ ]:
# Querying DataFrames with df.query(): More readable way to filter rows u
# Age > 30
df.query('Age > 30')

In [ ]:
df[df['Age > 30')   # check how to run dis with multipes lines of codes

In [111]:
# Combined conditions
df.query("Age > 70 and Sex == 'male'")

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
95,Mr. George B Goldschmidt,0,1,male,71.0,0,0,34.6542
115,Mr. Patrick Connors,0,3,male,70.5,0,0,7.7500
490,Mr. Ramon Artagaveytia,0,1,male,71.0,0,0,49.5042
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.0,0,0,30.0000
847,Mr. Johan Svensson,0,3,male,74.0,0,0,7.7750

In [112]:
# String match
df.query('Name == "Mr. Johan Svensson"')

                   Name  Survived  Pclass   Sex   Age  SibSp  PaCh   Fare
847  Mr. Johan Svensson         0       3  male  74.0      0     0  7.775

 ## Sorting

                   Name  Survived  Pclass   Sex   Age  SibSp  PaCh   Fare
847  Mr. Johan Svensson         0       3  male  74.0      0     0  7.775

In [115]:
## Sort by a column
df.sort_values(by='Age')

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583
827,Master. George Sibley Richards,1,2,male,0.83,1,1,18.7500
...,...,...,...,...,...,...,...,...
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000

In [116]:
# Descending order
df.sort_values(by='Age', ascending=False) ['Name']

627    Mr. Algernon Henry Wilson Barkworth
847                     Mr. Johan Svensson
490                 Mr. Ramon Artagaveytia
95                Mr. George B Goldschmidt
115                    Mr. Patrick Connors
                      ...
77            Master. Alden Gates Caldwell
466           Miss. Helene Barbara Baclini
641                  Miss. Eugenie Baclini
751               Master. Viljo Hamalainen
799         Master. Assad Alexander Thomas
Name: Name, Length: 887, dtype: object

In [117]:
# Descending order
df.sort_values(by='Age', ascending=False)

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500
...,...,...,...,...,...,...,...,...
77,Master. Alden Gates Caldwell,1,2,male,0.83,0,2,29.0000
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167

In [118]:
# You can also sort by multiple columns
df.sort_values(['Age', 'Fare'])
# Note: This sorts by the Age column first. If multiple rows have the exact same age,
# the code uses the Fare column to break the tie (also in ascending order, from lowest

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583
827,Master. George Sibley Richards,1,2,male,0.83,1,1,18.7500
...,...,...,...,...,...,...,...,...
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000

In [119]:
# Sort by index (the default)
df.sort_index()
# This will sort different if you used a different index like we did above

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,Rev. Juozas Montvila,0,2,male,27.0,0,0,13.0000
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000
884,Miss. Catherine Helen Johnston,0,3,female,7.0,1,2,23.4500
885,Mr. Karl Howell Behr,1,1,male,26.0,0,0,30.0000
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500

## Grouping (groupby)

In [120]:
# Group by class
class_group = df.groupby('Pclass')
# This alone is not useful, unless you use operation (like .sum() or .mean() ) to performing any underlying

In [121]:
# Aggregate functions
# Mean Fare per class
class_group['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.707707
Name: Fare, dtype: float64

In [123]:
# Total Fare per class
class_group['Fare'].sum()

Pclass
1    18177.4125
2     3801.8417
3     6675.6535
Name: Fare, dtype: float64

In [122]:
# Aggregate functions
# Mean Fare per class
class_group['Age'].mean()

Pclass
1    38.788981
2    29.868641
3    25.188747
Name: Age, dtype: float64

In [124]:
# Multiple aggregations
class_group.agg({'Fare': ['mean', 'max', 'min']})

             Fare
             mean       max  min
Pclass
1       84.154687  512.3292  0.0
2       20.662183   73.5000  0.0
3       13.707707   69.5500  0.0

In [125]:
# class task
# find the passengers with the max and min fare from each class
df[df['Fare'] == 512.3292]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
257,Miss. Anna Ward,1,1,female,35.0,0,0,512.3292
676,Mr. Thomas Drake Martinez Cardeza,1,1,male,36.0,0,1,512.3292
733,Mr. Gustave J Lesurer,1,1,male,35.0,0,0,512.3292

In [127]:
df[df['Fare'] == 73.5000]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
71,Mr. Ambrose Jr Hood,0,2,male,21.0,0,0,73.5
119,Mr. Stanley George Hickman,0,2,male,21.0,2,0,73.5
383,Mr. Charles Henry Davies,0,2,male,18.0,0,0,73.5
652,Mr. Leonard Mark Hickman,0,2,male,24.0,2,0,73.5
662,Mr. Lewis Hickman,0,2,male,32.0,2,0,73.5

In [126]:
df[df['Fare'] == 69.5500]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
158,Master. Thomas Henry Sage,0,3,male,5.0,8,2,69.55
179,Miss. Constance Gladys Sage,0,3,female,8.0,8,2,69.55
200,Mr. Frederick Sage,0,3,male,17.0,8,2,69.55
322,Mr. George John Jr Sage,0,3,male,20.0,8,2,69.55
788,Miss. Stella Anna Sage,0,3,female,21.0,8,2,69.55
842,Mr. Douglas Bullen Sage,0,3,male,18.0,8,2,69.55
859,Miss. Dorothy Edith Sage,0,3,female,14.0,8,2,69.55

In [128]:
# Simple condition
df[df['Fare'] == 0.0]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
178,Mr. Lionel Leonard,0,3,male,36.0,0,0,0.0
261,Mr. William Harrison,0,1,male,40.0,0,0,0.0
269,Mr. William Henry Tornquist,1,3,male,25.0,0,0,0.0
275,Mr. Francis Parkes,0,2,male,21.0,0,0,0.0
300,Mr. William Cahoone Jr Johnson,0,3,male,19.0,0,0,0.0
411,Mr. Alfred Fleming Cunningham,0,2,male,22.0,0,0,0.0
463,Mr. William Campbell,0,2,male,21.0,0,0,0.0
478,Mr. Anthony Wood Frost,0,2,male,37.0,0,0,0.0
594,Mr. Alfred Johnson,0,3,male,49.0,0,0,0.0
630,Mr. William Henry Marsh Parr,0,1,male,30.0,0,0,0.0
671,Mr. Ennis Hastings Watson,0,2,male,19.0,0,0,0.0
728,Mr. Robert J Knight,0,2,male,41.0,0,0,0.0
802,Mr. Thomas Jr Andrews,0,1,male,39.0,0,0,0.0
811,Mr. Richard Fry,0,1,male,39.0,0,0,0.0
818,Jonkheer. John George Reuchlin,0,1,male,38.0,0,0,0.0

## Renaming Columns and Indexes

In [129]:
# Renaming columns
# Use the rename() method with columns parameter:
df.rename(columns={'Name': 'FullName'}, inplace=True)

In [130]:
df

,FullName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,Rev. Juozas Montvila,0,2,male,27.0,0,0,13.0000
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000
884,Miss. Catherine Helen Johnston,0,3,female,7.0,1,2,23.4500
885,Mr. Karl Howell Behr,1,1,male,26.0,0,0,30.0000
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500

In [ ]:
# Renaming all columns at once
# df.columns = ['Full Name', 'Years Old']
# Make sure the number of values here match the number of columns

In [131]:
# Renaming index (row labels)

# I've hardly had to rename indexes
df.rename(index={0: 'First', 1: 'Second'}, inplace=True)
df.head()
# Notice the column order changes

,FullName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
First,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
Second,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500

In [132]:
df.reset_index(inplace=True, drop=True)
df.head()

,FullName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500

In [133]:
# Run this if you did the above (else, leave it)
df.drop(columns=['index'], inplace=True)

KeyError: "['index'] not found in axis"

## Adding Columns and Rows

In [134]:
# had to import the data again to reset, but this isn't
df = pd.read_csv('data/titanic.csv')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [135]:
# Adding a new column (with default or calculated values)
df['Status'] = 'Poor'

In [136]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Poor
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Poor
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [137]:
# fill the column based of certain condition
df.loc[df['Fare'] > 10, 'Status'] = 'Rich'

In [138]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [139]:
# fill the column based of certain condition
df.loc[df['Fare'] > 20, 'Status'] = 'Rich'     #

In [140]:
df.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.00,Rich
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.00,Rich
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45,Rich
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00,Rich
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.75,Poor

In [ ]:
# You can also use np.where to get the same result
import numpy as np
df['Status'] = np.where(df['Fare'] < 10, 'Poor', np.where(df['Fare'] < 50, 'Avg_rich', 'Rich'))

In [141]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor
...,...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000,Rich
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000,Rich
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500,Rich
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000,Rich
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500,Poor

In [ ]:
df.w
pd.w

In [143]:
#Inserting at a specific position
# Insert at column position 1
df.insert(1, 'ID', 101)

In [144]:
df.head()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,101,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,101,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,101,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,101,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,101,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [145]:
# Adding a row using loc (if index doesn’t exist)
# Add a new row at index 2
df.loc[2] = [1, 101, 1, 'Tomi Jesu', 'female', 22, 1, 0, 15.0, 'Rich']
df.head()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,101,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,101,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,101,1,Tomi Jesu,female,22.0,1,0,15.0000,Rich
3,1,101,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,101,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [146]:
# to add at the buttom you can also use concat (use pd.concat),
# before now, you could use append()

new_row = pd.DataFrame([[1, 101, 2, 'Funmi Ajagun.', 'female', 25, 1, 0, 15.0, 'Rich']], columns=df.columns)
new_row

   Survived   ID  Pclass           Name     Sex  Age  SibSp  PaCh  Fare Status
0         1  101       2  Funmi Ajagun.  female   25      1     0  15.0   Rich

In [147]:
df = pd.concat([df, new_row], ignore_index=True)

In [148]:
df.tail()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
883,1,101,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.00,Rich
884,0,101,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45,Rich
885,1,101,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00,Rich
886,0,101,3,Mr. Patrick Dooley,male,32.0,0,0,7.75,Poor
887,1,101,2,Funmi Ajagun.,female,25.0,1,0,15.00,Rich

In [149]:
# Dropping columns
df.drop(columns=['ID'], inplace=True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000,Rich
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [150]:
# Dropping using axis argument
# Drop column
df.drop('Status', axis=1, inplace=True)

In [151]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [153]:
# Drop row
df.drop(1, axis=0, inplace=True)

In [154]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583

# How to save you dataframe

In [ ]:
# take note to always drop the default pandas index (this is always added by default)
# secondly, you can also save to other file formats

In [156]:
df.to_csv('data/new_titanic.csv', index=False)

In [157]:
new_df = pd.read_csv('data/new_titanic.csv')
new_df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Tomi Jesu,female,22.0,1,0,15.0000
2,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
3,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
4,0,3,Mr. James Moran,male,27.0,0,0,8.4583
...,...,...,...,...,...,...,...,...
882,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
883,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
884,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
885,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500
886,1,2,Funmi Ajagun.,female,25.0,1,0,15.0000

## Pandas Data Inspection & Cleaning

For this section:
The data set contains some empty cells ("Date" in row 22, and "Calories" in row 18
and 28).
The data set contains wrong format ("Date" in row 26).
The data set contains wrong data ("Duration" in row 7).
The data set contains duplicates (row 11 and 12).

In [158]:
df = pd.read_csv('data/dirty_data.csv')

df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [160]:
# Handling Missing Data
# first, we need to identify missing values
# This function:
# Returns a new table of the exact same size as the original (don't do th
# Fills every spot with True if the value is missing (like NaN or None).
# Fills the spot with False if the value is present and valid
# Boolean DataFrame

df.isna() # or df.isnull()

# opposite is df.notna() or df.notnull() # To get True

    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False

In [163]:
# return only missing ones

df.loc[df.isna().any(axis=1), df.isna() .any(axis=0)]

            Date  Calories
18  '2020/12/18'       NaN
22           NaN     282.0
28  '2020/12/28'       NaN

In [164]:
df.isna().any   #

Duration    False
Date         True
Pulse       False
Maxpulse    False
Calories     True
dtype: bool

In [165]:
df.isna().all()  # check fo howmany rows

Duration    False
Date        False
Pulse       False
Maxpulse    False
Calories    False
dtype: bool

In [166]:
# to just return the count of NaNs per column
df.isna().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

## How to handle missing data                     2/09/26

1. Dropping Missing Data (dropna): If the missing data is
minimal (e.g., less than 5% of your dataset), you can remove
it using df.dropna()

In [167]:
# Drop missing values
# Drop rows with any NaNs
# Take note of the axis=0, how='any arguments

df.dropna(inplace=True)

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  29 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     29 non-null     int64
 3   Maxpulse  29 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [170]:
df = pd.read_csv('data/dirty_data.csv')

In [171]:
# Drop rows where all values are NaN
df.dropna(how='all', inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [172]:
# you can choose to drop from a particular row by using subset (just use a list)
# Drop rows where 'Date' is NaN

df.dropna(subset=['Date'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.5+ KB

In [ ]:
# Lastly, you can drop entire column
# Remove any column containing missing data.python
# We hardly do this in practice
# df.dropna(axis=1)

In [174]:
# We also have threshold (thresh):
# Keeps rows/columns only if they contain at least N non-null values.

df.dropna(thresh=3)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
Filling Missing Data (fillna): When you cannot afford to lose
data, you can replace missing cells with alternative values
using df.fillna()

In [175]:
df = pd.read_csv('data/dirty_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [177]:
# Constant value substitution: Fills every missing cell with a specific n
# Fill all NaNs with 0
# But this might not be suitable in all cases
df.fillna(0, inplace=True)

In [ ]:
# Fill with a default string (not really useful too)
# df['Calories'].fillna('Unknown')

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  32 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [179]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       0.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45             0    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       0.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [180]:
df = pd.read_csv('data/dirty_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
# Statitical Imputation (Numerical columns):
# Replaces missing data with the column's mean, median, or mode.
# df['Calories'].fillna(df['Calories'].mean(), inplace=True) # old way
df['Calories'] = df['Calories'].fillna(df['Calories'].mean())

In [181]:
df.isna() .sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [182]:
df.loc[df.isna().any(axis=1), df.isna().any(axis=0)]

            Date  Calories
18  '2020/12/18'       NaN
22           NaN     282.0
28  '2020/12/28'       NaN

In [183]:
df.duplicated().any()

np.True_

In [185]:
# Setting keep=False ensures all occurrences of the duplicate rows are ma
df.loc[df.duplicated(keep=False), :]

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7

In [187]:
# Drop duplicates

# Keep first by default
df.drop_duplicates(inplace=True)

In [191]:
df.duplicated().any()

np.False_

In [192]:
# Keep last occurrence
df.drop_duplicates(keep='last')
# I didn't actually run them on this

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Data Type Conversion

In [193]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      30 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.5+ KB

In [194]:
# Our maxpulse is int, let's change it to float
df['Maxpulse'] = df['Maxpulse'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      30 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     float64
 4   Calories  29 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.5+ KB

In [195]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110     130.0     409.1
1        60  '2020/12/02'    117     145.0     479.0
2        60  '2020/12/03'    103     135.0     340.0
3        45  '2020/12/04'    109     175.0     282.4
4        45  '2020/12/05'    117     148.0     406.0

## String Manipulation Using .str

In [196]:
df = pd.read_csv('data/titanic.csv')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [197]:
# Using our first dataset
df['Name'].str.lower() # all lowercase
# If i wanted to return an updated df
# df["Name"] = df["Name"].str.lower()

0                                 mr. owen harris braund
1      mrs. john bradley (florence briggs thayer) cum...
2                                  miss. laina heikkinen
3            mrs. jacques heath (lily may peel) futrelle
4                                mr. william henry allen
                             ...
882                                 rev. juozas montvila
883                          miss. margaret edith graham
884                       miss. catherine helen johnston
885                                 mr. karl howell behr
886                                   mr. patrick dooley
Name: Name, Length: 887, dtype: object

In [ ]:
# explore on your own
df['Name'].str.upper() # all uppercase
df['Name'].str.title() # title case
df['Name'].str.strip() # remove whitespace
df['Name'].str.replace(' ', '_') # replace space with underscore

# Combining DataFrames

In [198]:
# a. concat(): Combine along rows or columns
data1 = {
'Name': ['Rhoda', 'Jemilah', 'Rahmat', 'Esther'],
'Age': [25, 30, 35, 10],
'City': ['Ilorin', 'Lagos', 'Ibadan', 'Abuja']
}
df1 = pd.DataFrame(data1)
df1

      Name  Age    City
0    Rhoda   25  Ilorin
1  Jemilah   30   Lagos
2   Rahmat   35  Ibadan
3   Esther   10   Abuja

In [199]:
data2 = {
'Name': ['Abiola', 'Nofisat', 'Salamat', 'Lola'],
'Age': [20, 20, 35, 11],
'City': ['Abuja', 'Akure', 'Mina', 'Kano']
}
df2 = pd.DataFrame(data2)
df2

      Name  Age   City
0   Abiola   20  Abuja
1  Nofisat   20  Akure
2  Salamat   35   Mina
3     Lola   11   Kano

In [200]:
# Stack rows
# remember the concat we did earlier?
# remeber to ignore index
pd.concat([df1, df2], axis=0, ignore_index=True)

      Name  Age    City
0    Rhoda   25  Ilorin
1  Jemilah   30   Lagos
2   Rahmat   35  Ibadan
3   Esther   10   Abuja
4   Abiola   20   Abuja
5  Nofisat   20   Akure
6  Salamat   35    Mina
7     Lola   11    Kano

In [201]:
# Side-by-side
# we don't need to ignore index here
pd.concat([df1, df2], axis=1)

      Name  Age    City     Name  Age   City
0    Rhoda   25  Ilorin   Abiola   20  Abuja
1  Jemilah   30   Lagos  Nofisat   20  Akure
2   Rahmat   35  Ibadan  Salamat   35   Mina
3   Esther   10   Abuja     Lola   11   Kano

In [202]:
# merge(): SQL-style joins on columns
# Inner join by default

pd.merge(df1, df2, on='Age')

# combines df1 and df2 side-by-side by matching rows that share the same value
# Includes only matching keys from both DataFrames. Rows with keys that don't

   Name_x  Age  City_x   Name_y City_y
0  Rahmat   35  Ibadan  Salamat   Mina